apiVersion: v1
entries:
  aws-privateca-issuer:
  - apiVersion: v2
    appVersion: v1.8.1-2-gfb6b836
    created: "2026-04-16T11:10:40.807529+01:00"
    description: An addon for cert-manager to sign certificates using AWS PCA
    digest: 5fe33d67c9fbe964546c13b60fdd84339d1a15ecc997a5b4b3e47cb1e2a21d05
    name: aws-privateca-issuer
    type: application
    urls:
    - aws-privateca-issuer-v1.8.1-2-gfb6b836.tgz
    - https://github.com/nickperry/aws-privateca-issuer/releases/download/aws-privateca-issuer-v1.8.1-2-gfb6b836/aws-privateca-issuer-v1.8.1-2-gfb6b836.tgz
    version: v1.8.1-2-gfb6b836
generated: "2026-04-16T11:10:41.174798+01:00"
